author:
    type:         rest
    resource:     "App\\Controller\\AuthorController"
    name_prefix:  api_

book:
    type:         rest
    resource:     "App\\Controller\\BookController"
    name_prefix:  api_

user:
    type:         rest
    resource:     "App\\Controller\\UserController"
    name_prefix:  api_
