services:
    app.services.author:
        class: App\Services\Author
        arguments: [ '@repository.author', '@validator' ]

    app.services.book:
        class: App\Services\Book
        arguments: [ '@repository.book', '@validator' ]

    app.services.user:
        class: App\Services\User
        arguments: [ '@repository.user', '@validator' ]

    app.services.user_group:
        class: App\Services\UserGroup
        arguments: [ '@repository.user_group', '@validator' ]
