# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.exception_listener:
        class: App\EventListener\ExceptionListener
        arguments: [ '@kernel', '@logger' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    app.monolog_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments: [ ~, ~, true ]

    repositoryAuthor:
        class: Doctrine\ORM\EntityRepository
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - App\Entity\Author

    app.services.author:
        class: App\Services\Author
        arguments:
            - '@repositoryAuthor'
            - '@validator'

    jms_serializer.cache_naming_strategy:
        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy